        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 06 14:02:00 2016
        MODULE RUSCONSOLE__genmod
          INTERFACE 
            SUBROUTINE RUSCONSOLE
            END SUBROUTINE RUSCONSOLE
          END INTERFACE 
        END MODULE RUSCONSOLE__genmod
